name: Build and Test

on:
  push:
  pull_request:
    branches: [main]

env:
  DOTNET_VERSION: "7.0.304"

jobs:
  build-and-test:
    name: build-and-test-ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Format code
        run: dotnet format --verify-no-changes --verbosity diagnostic

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
        
      - name: Publish FruitApi
        run: dotnet publish FruitApi/FruitApi.csproj -c Release -o fruitApi

      - name: Upload a FruitApi Artifact
        uses: actions/upload-artifact@v3
        with:
          name: fruitApi
          path: fruitApi/**
          if-no-files-found: error
    
